**Assignment 1:**
* Create an array of integers between -10 and 10
   Run the following code to create a NumPy array D
   D = np.array(range(18)) + 3
* Extract every other value from array D starting from the 2nd value through 
the 10th value. Store the result in a variable called x.
* Extract every other value from array D starting from the 10th value through the 2nd value. Store the result in a variable called y.
* Create a variable z that contains all of the values in D in reverse order.
* How are NumPy Arrays better than Lists in Python?  
* Explain the data types supported by Numpy.


In [47]:
import numpy as np
import random


Create an array of integers between -10 and 10 Run the following code to create a NumPy array D D = np.array(range(18)) + 3

In [48]:
arr = np.random.randint(-10,10,(6,5))
arr

array([[-10,   4,  -7,  -9,   8],
       [ -5,   9,   4,  -7,  -4],
       [-10,   8,   5,   2,   6],
       [  4,   7,   9,  -7,  -1],
       [  4,   4,   6,   2,  -3],
       [  5,   8,  -2,  -1,   5]])

In [49]:
D = np.array(range(18)) + 3
D

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

Extract every other value from array D starting from the 2nd value through the 10th value. Store the result in a variable called x.

In [50]:
x = D[1:10]
x

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

Extract every other value from array D starting from the 10th value through the 2nd value. Store the result in a variable called y.

In [60]:
y = D[9:0:-1]
y

array([12, 11, 10,  9,  8,  7,  6,  5,  4])

Create a variable z that contains all of the values in D in reverse order.

In [61]:
z = D[::-1]
z

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3])

How are NumPy Arrays better than Lists in Python?


In [ ]:
'''Ans: Although both behaves same but there are differences between the two:-
-Numpy array is a library developed using C language but list is a data structure developed in python.
-Numpy is Faster that that of List.
-Numpy takes less memory for allocation than List.
-Numpy used in high end numerical computaions whereas, list are widely used for storing objects in programming.'''

Explain the data types supported by Numpy.

In [ ]:
'''Numpy supports more datatypes regardless of Python:-
-Boolean
-Integer
-Float
-unsigned Integer
-TimeDelta
-Unsigned Float
-String
-Unicode String
-chunk of memory(Void)
-Coimplex Float
-Object
'''