**ASSIGNMENT-2**
imply all the functions learned on this day in this data set https://www.kaggle.com/uciml/pima-indians-diabetes-database 


PERFORMING DATA ANALYISIS ON DIABETES DATASET

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 
# for working script in notebook


importing and reading Diabetes dataset using numpy and pandas library

In [2]:
df = pd.read_csv("/content/drive/MyDrive/GC/Diabetes/diabetes.csv")

OPERATIONS USING NUMPY

In [16]:
x= np.linspace(df['Age'][2],df['Age'][200],30)
x  # giving 1D-Array.... 50 values between Age 2 index - Age 200 index with nos. of values is 30

array([32.        , 31.62068966, 31.24137931, 30.86206897, 30.48275862,
       30.10344828, 29.72413793, 29.34482759, 28.96551724, 28.5862069 ,
       28.20689655, 27.82758621, 27.44827586, 27.06896552, 26.68965517,
       26.31034483, 25.93103448, 25.55172414, 25.17241379, 24.79310345,
       24.4137931 , 24.03448276, 23.65517241, 23.27586207, 22.89655172,
       22.51724138, 22.13793103, 21.75862069, 21.37931034, 21.        ])

In [17]:
# create an array of evenly spaced values with step
arr = np.arange(df['Age'][10],df['Age'][20],2)
arr

array([], dtype=int64)

In [ ]:
# how do you convert a list to a np array

list1 = [5,10,15,20,25,30,50]
arr1 = np.asarray(list1)

print(arr1)

type(arr1)

In [24]:
arr = np.random.randint(10,500,(10,5)) #10x5 matrix
arr

array([[326, 296,  96, 204, 312],
       [ 81, 390, 369, 444, 496],
       [315,  63, 137, 336, 285],
       [287, 257,  58, 107, 457],
       [429, 124, 316, 325, 284],
       [199, 366, 382,  93, 303],
       [ 91,  78,  21, 124, 256],
       [460,  12,  96, 248, 460],
       [412, 204,  87, 485, 451],
       [208, 469, 423,  19, 497]])

In [25]:
arr.shape # getting the dimensions size

(10, 5)

In [27]:
arr.ndim  ### number of dimensions

2

In [29]:
arr.size

50

50

In [31]:
#Arithmetic Operation on age feature
a = np.linspace(df['Age'][1],df['Age'][100],30)
b = np.linspace(df['Age'][101],df['Age'][200],30)
a

array([31.        , 31.06896552, 31.13793103, 31.20689655, 31.27586207,
       31.34482759, 31.4137931 , 31.48275862, 31.55172414, 31.62068966,
       31.68965517, 31.75862069, 31.82758621, 31.89655172, 31.96551724,
       32.03448276, 32.10344828, 32.17241379, 32.24137931, 32.31034483,
       32.37931034, 32.44827586, 32.51724138, 32.5862069 , 32.65517241,
       32.72413793, 32.79310345, 32.86206897, 32.93103448, 33.        ])

In [32]:
b

array([22.        , 21.96551724, 21.93103448, 21.89655172, 21.86206897,
       21.82758621, 21.79310345, 21.75862069, 21.72413793, 21.68965517,
       21.65517241, 21.62068966, 21.5862069 , 21.55172414, 21.51724138,
       21.48275862, 21.44827586, 21.4137931 , 21.37931034, 21.34482759,
       21.31034483, 21.27586207, 21.24137931, 21.20689655, 21.17241379,
       21.13793103, 21.10344828, 21.06896552, 21.03448276, 21.        ])

In [33]:
a/b # division 

array([1.40909091, 1.4144427 , 1.41981132, 1.42519685, 1.43059937,
       1.43601896, 1.4414557 , 1.44690967, 1.45238095, 1.45786963,
       1.4633758 , 1.46889952, 1.47444089, 1.48      , 1.48557692,
       1.49117175, 1.49678457, 1.50241546, 1.50806452, 1.51373183,
       1.51941748, 1.52512156, 1.53084416, 1.53658537, 1.54234528,
       1.54812398, 1.55392157, 1.55973813, 1.56557377, 1.57142857])

In [35]:
np.add(a,b)  #Alternative to a+b
#or
a+b

array([53.        , 53.03448276, 53.06896552, 53.10344828, 53.13793103,
       53.17241379, 53.20689655, 53.24137931, 53.27586207, 53.31034483,
       53.34482759, 53.37931034, 53.4137931 , 53.44827586, 53.48275862,
       53.51724138, 53.55172414, 53.5862069 , 53.62068966, 53.65517241,
       53.68965517, 53.72413793, 53.75862069, 53.79310345, 53.82758621,
       53.86206897, 53.89655172, 53.93103448, 53.96551724, 54.        ])

In [41]:
np.subtract(a,b) #a,b or b,a can be passed as args
#or
a-b

array([ 9.        ,  9.10344828,  9.20689655,  9.31034483,  9.4137931 ,
        9.51724138,  9.62068966,  9.72413793,  9.82758621,  9.93103448,
       10.03448276, 10.13793103, 10.24137931, 10.34482759, 10.44827586,
       10.55172414, 10.65517241, 10.75862069, 10.86206897, 10.96551724,
       11.06896552, 11.17241379, 11.27586207, 11.37931034, 11.48275862,
       11.5862069 , 11.68965517, 11.79310345, 11.89655172, 12.        ])

In [42]:
a_transpose = np.transpose(a)  # transpose the matrix
a_transpose

array([31.        , 31.06896552, 31.13793103, 31.20689655, 31.27586207,
       31.34482759, 31.4137931 , 31.48275862, 31.55172414, 31.62068966,
       31.68965517, 31.75862069, 31.82758621, 31.89655172, 31.96551724,
       32.03448276, 32.10344828, 32.17241379, 32.24137931, 32.31034483,
       32.37931034, 32.44827586, 32.51724138, 32.5862069 , 32.65517241,
       32.72413793, 32.79310345, 32.86206897, 32.93103448, 33.        ])

OPERATIONS USING PANDAS

In [43]:
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [44]:
df.tail()

Pregnancies  Glucose  ...  Age  Outcome
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[5 rows x 9 columns]

In [45]:
df.info  #### Gives all the information about your dataframe

<bound method DataFrame.info of      Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]>

In [50]:
#renaming the features
df = df.rename(columns={'BMI':'BodyMassIdx', 'Insulin':'Insuline'}) 
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [51]:
df.shape

(768, 9)

In [52]:
df.columns # to get the columns/ features' name

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insuline',
       'BodyMassIdx', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [54]:
df.isnull().sum() ### To check the number of missing values

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insuline                    0
BodyMassIdx                 0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Hence we got no null/ missing values

In [55]:
df.value_counts('Age')  ## count the number of values based on the labels

Age
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
38    16
36    16
32    16
45    15
34    14
40    13
43    13
46    13
39    12
35    10
52     8
44     8
50     8
51     8
58     7
54     6
47     6
53     5
60     5
49     5
57     5
48     5
66     4
62     4
63     4
55     4
59     3
56     3
65     3
67     3
61     2
69     2
64     1
68     1
70     1
72     1
81     1
dtype: int64

This dataframe shows that the young persons are more than that of the senior cizens