**Assignment 1: Do operations on 2d array using numpy**

In [2]:
import numpy as np
#Using List
arr = np.array([1,2,3,4,5,6])
arr
type(arr)

numpy.ndarray

In [14]:
#Using Tuple
arr = np.array((1,2,3,4,5,6))
type(arr)


numpy.ndarray

In [15]:
#Checking dimension
arr.ndim

1

Operation on 2d  arrray

In [9]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
#Checking dimension
arr2.ndim

2

Operation on 3d array

In [12]:
arr3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
#Checking dimension
arr3.ndim

3

Operation on multi-dimensional array

In [19]:
mularr = np.array([1,2,3,4], ndmin=5)
mularr

array([[[[[1, 2, 3, 4]]]]])

In [21]:
#Checking dimension
mularr.ndim

5